In [57]:
import pandas as pd

df_rentasPV = pd.read_csv("Data_Raw/rentas_PV.csv", sep=";", encoding="utf-8-sig")

In [58]:
print(df_rentasPV.shape)

(1925, 4)

In [59]:
df_rentasPV

     ambitos territoriales               tipo de renta   sexo   2016
0          C.A. de Euskadi                 Renta total  Total  20443
1          C.A. de Euskadi           Renta del trabajo  Total  12182
2          C.A. de Euskadi    Renta capital mobiliario  Total   1236
3          C.A. de Euskadi  Renta capital inmobiliario  Total    425
4          C.A. de Euskadi        Renta de actividades  Total    963
...                    ...                         ...    ...    ...
1920             Zumarraga    Renta capital mobiliario  Total    788
1921             Zumarraga  Renta capital inmobiliario  Total    209
1922             Zumarraga        Renta de actividades  Total    706
1923             Zumarraga              Transferencias  Total   6579
1924             Zumarraga            Renta disponible  Total  17701

[1925 rows x 4 columns]

In [60]:
df_rentasPV = df_rentasPV.drop(columns=["sexo"]) #Eliminamos la columan sexo
df_rentasPV

     ambitos territoriales               tipo de renta   2016
0          C.A. de Euskadi                 Renta total  20443
1          C.A. de Euskadi           Renta del trabajo  12182
2          C.A. de Euskadi    Renta capital mobiliario   1236
3          C.A. de Euskadi  Renta capital inmobiliario    425
4          C.A. de Euskadi        Renta de actividades    963
...                    ...                         ...    ...
1920             Zumarraga    Renta capital mobiliario    788
1921             Zumarraga  Renta capital inmobiliario    209
1922             Zumarraga        Renta de actividades    706
1923             Zumarraga              Transferencias   6579
1924             Zumarraga            Renta disponible  17701

[1925 rows x 3 columns]

In [61]:
df_rentasPV = df_rentasPV.rename(columns={"2016": "total_2016"}) #CAMBIAMOS NOMBRE COLUMNA
df_rentasPV

     ambitos territoriales               tipo de renta  total_2016
0          C.A. de Euskadi                 Renta total       20443
1          C.A. de Euskadi           Renta del trabajo       12182
2          C.A. de Euskadi    Renta capital mobiliario        1236
3          C.A. de Euskadi  Renta capital inmobiliario         425
4          C.A. de Euskadi        Renta de actividades         963
...                    ...                         ...         ...
1920             Zumarraga    Renta capital mobiliario         788
1921             Zumarraga  Renta capital inmobiliario         209
1922             Zumarraga        Renta de actividades         706
1923             Zumarraga              Transferencias        6579
1924             Zumarraga            Renta disponible       17701

[1925 rows x 3 columns]

In [62]:
df_rentasPV = df_rentasPV.pivot_table(
    index="ambitos territoriales",
    columns="tipo de renta",
    values="total_2016"
).reset_index() #Pivotamos la tabla para que se vea mas claro

In [63]:
df_rentasPV

tipo de renta,ambitos territoriales,Renta capital inmobiliario,Renta capital mobiliario,Renta de actividades,Renta del trabajo,Renta disponible,Renta total,Transferencias
0,Abadi�o,262.0,967.0,695.0,13824.0,17620.0,20907.0,5158.0
1,Abaltzisketa,338.0,833.0,1614.0,12495.0,17690.0,20659.0,5379.0
2,Abanto y Ci�rvana-Abanto Zierbena,150.0,418.0,661.0,11485.0,14941.0,17514.0,4798.0
3,Aduna,610.0,724.0,1506.0,15775.0,19276.0,22779.0,4165.0
4,Agurain/Salvatierra,257.0,477.0,747.0,11576.0,15216.0,17689.0,4631.0
...,...,...,...,...,...,...,...,...
270,Ziortza-Bolibar,294.0,1653.0,1495.0,12350.0,17749.0,20846.0,5055.0
271,Zizurkil,521.0,969.0,703.0,12138.0,17222.0,20115.0,5784.0
272,Zuia,470.0,911.0,1438.0,17102.0,19919.0,24566.0,4645.0
273,Zumaia,436.0,1673.0,984.0,13480.0,18725.0,22234.0,5662.0
274,Zumarraga,209.0,788.0,706.0,12189.0,17701.0,20472.0,6579.0

In [64]:
df_rentasPV = df_rentasPV.rename(columns={"tipo de renta": "Id"})

In [65]:
# Convertir todas las columnas excepto 'ambitos territoriales' a Int64
cols_int = [col for col in df_rentasPV.columns if col != "ambitos territoriales"]

for col in cols_int:
    df_rentasPV[col] = pd.to_numeric(df_rentasPV[col], errors="coerce").astype("Int64")

print(df_rentasPV.dtypes)

tipo de renta
ambitos territoriales         object
Renta capital inmobiliario     Int64
Renta capital mobiliario       Int64
Renta de actividades           Int64
Renta del trabajo              Int64
Renta disponible               Int64
Renta total                    Int64
Transferencias                 Int64
dtype: object

In [66]:
df_rentasPV

tipo de renta,ambitos territoriales,Renta capital inmobiliario,Renta capital mobiliario,Renta de actividades,Renta del trabajo,Renta disponible,Renta total,Transferencias
0,Abadi�o,262,967,695,13824,17620,20907,5158
1,Abaltzisketa,338,833,1614,12495,17690,20659,5379
2,Abanto y Ci�rvana-Abanto Zierbena,150,418,661,11485,14941,17514,4798
3,Aduna,610,724,1506,15775,19276,22779,4165
4,Agurain/Salvatierra,257,477,747,11576,15216,17689,4631
...,...,...,...,...,...,...,...,...
270,Ziortza-Bolibar,294,1653,1495,12350,17749,20846,5055
271,Zizurkil,521,969,703,12138,17222,20115,5784
272,Zuia,470,911,1438,17102,19919,24566,4645
273,Zumaia,436,1673,984,13480,18725,22234,5662
274,Zumarraga,209,788,706,12189,17701,20472,6579

In [67]:
import os

# Exportar a CSV
df_rentasPV.to_csv(os.path.join("Data_Limpia/rentas_PV.csv"), index=False)

print("✅ Archivo guardado en: Pre - Proyecto/Data_Limpia/rentas_PV_2016.csv")

✅ Archivo guardado en: Pre - Proyecto/Data_Limpia/rentas_PV_2016.csv