In [2]:
import pandas as pd

df_poblacion = pd.read_csv("../Data_Raw/addinfo.csv", sep=",")

In [3]:
df_poblacion

               poblacion     source      valor
0         Total Nacional   Empresas  3.337.646
1            02 Albacete   Empresas     26.743
2    03 Alicante/Alacant   Empresas    138.964
3             04 Almería   Empresas     42.931
4         01 Araba/Álava   Empresas     19.147
..                   ...        ...        ...
101        47 Valladolid  Poblacion    519.851
102            49 Zamora  Poblacion    174.549
103          50 Zaragoza  Poblacion    954.811
104             51 Ceuta  Poblacion     85.144
105           52 Melilla  Poblacion     86.384

[106 rows x 3 columns]

In [4]:
# Eliminar puntos de miles y convertir a Int64
df_poblacion["valor"] = (
    df_poblacion["valor"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
    .astype("Int64")
)

print(df_poblacion.dtypes)
print(df_poblacion.shape)
df_poblacion.head()

poblacion    object
source       object
valor         Int64
dtype: object
(106, 3)

             poblacion    source    valor
0       Total Nacional  Empresas  3337646
1          02 Albacete  Empresas    26743
2  03 Alicante/Alacant  Empresas   138964
3           04 Almería  Empresas    42931
4       01 Araba/Álava  Empresas    19147

In [5]:
split = df_poblacion["poblacion"].str.split(" ", n=1, expand=True)

df_poblacion["cod_provincia"] = split[0]  
df_poblacion["poblacion"]     = split[1]  

print(df_poblacion.head())

          poblacion    source    valor cod_provincia
0          Nacional  Empresas  3337646         Total
1          Albacete  Empresas    26743            02
2  Alicante/Alacant  Empresas   138964            03
3           Almería  Empresas    42931            04
4       Araba/Álava  Empresas    19147            01

In [6]:
df_poblacion = df_poblacion[df_poblacion["poblacion"] != "Nacional"] #Eliminamos la fila que agrupa todo

In [7]:
df_poblacion

            poblacion     source   valor cod_provincia
1            Albacete   Empresas   26743            02
2    Alicante/Alacant   Empresas  138964            03
3             Almería   Empresas   42931            04
4         Araba/Álava   Empresas   19147            01
5            Asturias   Empresas   68688            33
..                ...        ...     ...           ...
101        Valladolid  Poblacion  519851            47
102            Zamora  Poblacion  174549            49
103          Zaragoza  Poblacion  954811            50
104             Ceuta  Poblacion   85144            51
105           Melilla  Poblacion   86384            52

[104 rows x 4 columns]

In [10]:
import os

# Exportar a CSV
df_poblacion.to_csv(os.path.join("../Output/poblacion.csv"), index=False) 

print("✅ Archivo guardado en: Pre - Proyecto/Output/poblacion.csv")

✅ Archivo guardado en: Pre - Proyecto/Output/poblacion.csv